name: Optimize Resource Packs
on:
  push:
    branches:
      - main  # Only trigger on the main branch
    paths:
      - 'packs/prison/**'
      - 'packs/hub/**'  # Only trigger if files in these directories change

jobs:
  determine-pack:
    name: Determine Modified Pack
    runs-on: ubuntu-latest
    outputs:
      packs: ${{ steps.filter.outputs.packs }}
    steps:
      - name: Checkout Repository with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure we have at least one previous commit for git diff

      - name: Check for Modified Files
        id: filter
        run: |
          PACKS=()
          BEFORE_COMMIT=$(git rev-parse HEAD^ || echo "")
          if [ -n "$BEFORE_COMMIT" ]; then
            if git diff --name-only $BEFORE_COMMIT HEAD | grep -q "^packs/prison/"; then
              PACKS+=("\"prison\"")
            fi
            if git diff --name-only $BEFORE_COMMIT HEAD | grep -q "^packs/hub/"; then
              PACKS+=("\"hub\"")
            fi
          fi
          echo "packs=$(echo "[${PACKS[*]}]")" >> $GITHUB_OUTPUT
        shell: bash

  packsquash:
    needs: determine-pack
    if: ${{ needs.determine-pack.outputs.packs != '[]' }}  # Run only if at least one pack is modified
    name: Optimize Resource Pack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack_name: ${{ fromJson(needs.determine-pack.outputs.packs) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run PackSquash on ${{ matrix.pack_name }}
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'packs/${{ matrix.pack_name }}'

      - name: Debug PackSquash Output
        run: ls -R packs/${{ matrix.pack_name }}

      - name: Create Release for ${{ matrix.pack_name }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ matrix.pack_name }}-v${{ github.run_number }}
          files: packs/${{ matrix.pack_name }}/pack.zip
