name: Optimize Resource Packs

on:
  push:
    branches:
      - main
    paths:
      - 'packs/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      modified_packs: ${{ steps.get_modified_packs.outputs.modified }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get modified packs
        id: get_modified_packs
        run: |
          MODIFIED_PACKS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packs/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "Modified packs: $MODIFIED_PACKS"
          echo "modified=$MODIFIED_PACKS" >> "$GITHUB_OUTPUT"

  packsquash:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.modified_packs != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack_name: ${{ fromJson(needs.detect-changes.outputs.modified_packs) }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PackSquash on ${{ matrix.pack_name }}
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'packs/${{ matrix.pack_name }}'

      - name: Debug PackSquash output
        run: ls -R

      - name: Tag and create release for ${{ matrix.pack_name }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ matrix.pack_name }}-v${{ github.run_number }}
          files: packs/${{ matrix.pack_name }}/pack.zip
