name: Optimize resource pack
on:
  push:
    branches:
      - main  # Only trigger on pushes to the main branch

jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # A non-shallow repository clone is required
          
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'pack'
            
      - name: Debug PackSquash output
        run: ls -R  # Verify the output directory and files

      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Ensure the token has repo permissions
        with:
          tag_name: action-v${{ github.run_number }}
          files: pack/pack.zip  # Ensure the correct file path
