name: Optimize Resource Packs
on:
  push:
    branches:
      - main  # Only trigger on main branch
    paths:
      - 'packs/prison/**'
      - 'packs/hub/**'  # Only trigger if files in these directories change

jobs:
  determine-pack:
    name: Determine Modified Packs
    runs-on: ubuntu-latest
    outputs:
      packs: ${{ steps.filter.outputs.packs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Changed Packs
        id: filter
        run: |
          PACKS=()
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^packs/prison/"; then
            PACKS+=("prison")
          fi
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^packs/hub/"; then
            PACKS+=("hub")
          fi
          echo "packs=$(jq -c --null-input '$ARGS.positional' --args "${PACKS[@]}")" >> $GITHUB_OUTPUT
        shell: bash

  packsquash:
    needs: determine-pack
    if: ${{ needs.determine-pack.outputs.packs != '[]' }}  # Run only if changes were detected
    name: Optimize Resource Packs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pack_name: ${{ fromJson(needs.determine-pack.outputs.packs) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run PackSquash on ${{ matrix.pack_name }}
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'packs/${{ matrix.pack_name }}'

      - name: Move Pack to Common Folder
        run: |
          mkdir -p artifacts
          mv packs/${{ matrix.pack_name }}/pack.zip artifacts/${{ matrix.pack_name }}.zip

      - name: Upload Pack as Artifact (for debugging)
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.pack_name }}-zip
          path: artifacts/${{ matrix.pack_name }}.zip

  release:
    needs: [determine-pack, packsquash]
    if: ${{ needs.determine-pack.outputs.packs != '[]' }}
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download All Pack Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Debug: List Artifact Files
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: release-v${{ github.run_number }}
          files: artifacts/**/*.zip  # Upload all modified packs
          body: "Optimized resource packs for latest changes."